services:
  # Python Backend (Free Tier)
  - type: web
    name: issue-tracker-api
    runtime: python
    # "Free" instance type
    plan: free
    buildCommand: pip install -r requirements.txt
    # Start app and use local SQLite file (Data resets on restart in free tier!)
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
